### ISSUE TITLE
Bug in Demo

### ISSUE THREAD

**Issue by gesundelehre** [OokTech/TW5-PhotoGallery#1]
Hello there, 

i found a bug in the demo of the Photo Gallery - why is there no tiddler with the name "Edit Photo Gallery"

It should be located here: https://ooktech.com/TiddlyWiki/PhotoGallery/#%24%3A%2Fplugins%2Finmysocks%2FPhoto%20Gallery%2FEdit%20Photo%20Gallery

It would be good if you could solve this. Thanks

**Comment by inmysocks** [comment]
That is a typo in the documentation. The tiddler is actually here https://ooktech.com/TiddlyWiki/PhotoGallery/#%24%3A%2Fplugins%2FOokTech%2FPhoto%20Gallery%2FEdit%20Photo%20Gallery

I will try to update that and put up the fixed version later today.

**Comment by inmysocks** [comment]
The demo has been corrected.
