### ISSUE TITLE
Navigation bar "Prev-Next" on every tiddler

### ISSUE THREAD

**Issue by protw** [OokTech/TW5-PhotoGallery#2]
I work with TW5 5.1.14. Everything works just great so far, except one thing, namely: every tiddler contains the navigation bar "Prev-Next", whereas the [example at ooktech.com](http://ooktech.com/jed/ExampleWikis/PhotoGallery/) displays the navigation bar at gallery tiddlers only!?

What's wrong?

![image](https://user-images.githubusercontent.com/1643432/30875925-a10812ce-a2fd-11e7-9c93-680788e1d276.png)

**Comment by inmysocks** [comment]
I have not been able to replicate this problem without manually editing the view templates. How did you install the plugin?

The worked for me when I did this:

- Download an empty wiki
- Install the plugin by dragging and dropping from https://ooktech.com/TiddlyWiki/PhotoGallery into the empty wiki
- Reload the wiki
  - No tiddlers display the gallery navigation buttons
- Import some image files
  - Only image tiddlers have the gallery navigation buttons

**Comment by protw** [comment]
I use TW 5.1.14 over Node.js. First, by mistake, I installed PhotoGallery v. 0.0.2 drag-and-dropping it from example http://ooktech.com/jed/ExampleWikis/PhotoGallery/. After that the navigation bar Prev-Next appeared. Then I deleted .tid file of that plugin and drag-and-dropped v. 0.0.4 of the plugin from https://ooktech.com/TiddlyWiki/PhotoGallery/. However, the navigation bar Prev-Next did not disappeared. That's it.

**Comment by inmysocks** [comment]
It sounds like a shadow tiddler got modified before you removed the old plugin. Go to the system tiddler tab of advanced search and search for

$:/plugins/inmysocks/PhotoGallery

and delete any tiddlers that show up.

**Comment by protw** [comment]
I've got similar but another path, namely: $:/plugins/OokTech/PhotoGallery.tid

So I deleted all the files containing the word `gallery` but it did not help. Also I tried to install the plugin through the library - the result is the same.

As you may see tiddlers with external images contain even two navigation strips. The upper one of them has a stable look having the arrow `Next` and no arrow `Prev`. A look of another strip depends on the image index in the gallery: first, in the middle, last.

![image](https://user-images.githubusercontent.com/1643432/30909823-20756fba-a38b-11e7-83da-674b7630c6f7.png)

**Comment by inmysocks** [comment]
When you have a single image part of multiple galleries than it will have one navigation bar per gallery at the top of the tiddler, so that is expected behaviour.

The problem seems to be that there is modified version of the view template from the plugin in your wiki that isn't correctly identifying image tiddlers so it is displaying on all tiddlers.

Or there is a gallery defined in the gallery editor tiddler (called $:/plugins/OokTech/Photo Gallery/Edit Photo Gallery) that is somehow counting all tiddlers as images. I am not sure how either one would happen though unless you manually modified the view templates.

**Comment by protw** [comment]
No way I've modified template or other system code. I use Tiddlymap and Font Awesome plugins (both described at http://tiddlymap.org/). They potentially could interfere with template or other code. So far I've no any other idea. A bit later I'll try to test a blank TW containing just photos and your plugin and then inform you about results.

**Comment by protw** [comment]
EUREKA! I've caught the point. 

The spare navigation strip is displayed when I import any image file except `JPG` one, i.e. `PNG`, `GIF`, etc. 

Having looked your file `$:/plugins/OokTech/Photo Gallery/galleryTemplateHeader` I noticed several similar filter expressions: `filter='[is[current]]+[type[image/jpeg]][type[image/gif]][type[image/x-icon]][type[image/png]][type[image/svg+xml]]+[nsort[order]]'`.

As far as I understand the filtering sintax, the sign `+` in the fragment `+[type[image/jpeg]][type[image/gif]][type[image/x-icon]][type[image/png]][type[image/svg+xml]]` properly affects `jpeg` type only, which is immediately next to the sign `+`, and does not affect all the rest types: `gif`, `x-icon`, `png`, and `svg+xml`. It's just my assumption.

So now I'm forced to limit plugin's use by `jpg` type only.

I'm grateful for the discussion and would be even more grateful for explanation and correction of the plugin.

**Comment by inmysocks** [comment]
I guess that is what I get for trying to be cleaver. I will update the plugin and upload the new version in a few minutes.

**Comment by protw** [comment]
Just let me know about update

**Comment by inmysocks** [comment]
It is updated to 0.0.5 now on https://ooktech.com/TiddlyWiki/PhotoGallery and in the plugin library.

**Comment by protw** [comment]
Great, thanks
